#  class 1)  for numpy array

In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
mylist

[1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
mylist_1=[[1,2,3],[22.44]]

In [9]:
mylist_1

[[1, 2, 3], [22.44]]

In [10]:
my_matrix=np.array(mylist_1)
my_matrix

array([list([1, 2, 3]), list([22.44])], dtype=object)

In [11]:
my_matrix.shape

(2,)

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Broadcasting the numpy
np.ones((5,5))*4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [18]:
np.ones((5,5))/4

array([[0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25]])

In [19]:
[1,1,1,1] + 10

TypeError: can only concatenate list (not "int") to list

In [20]:
np.linspace(10,20,50)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
#################################################################################################################3

# Class2) Numpy Array  part--2

In [23]:
import numpy as np

In [24]:
np.random.rand(1)

array([0.73391392])

In [25]:
np.random.rand(5,5)

array([[0.77934274, 0.99892302, 0.37838647, 0.00446884, 0.55481046],
       [0.29964579, 0.16967562, 0.63365864, 0.95793254, 0.85156402],
       [0.65604397, 0.09506471, 0.71217591, 0.03589858, 0.0445719 ],
       [0.68774132, 0.96175048, 0.18420917, 0.24457306, 0.03003715],
       [0.15006104, 0.67001002, 0.10966179, 0.93148345, 0.60333742]])

In [26]:
np.random.randn(1)

array([0.55143337])

In [27]:
np.random.randn(5,5)

array([[ 0.79824115,  0.4802167 ,  0.91670488, -0.99091686, -0.84076534],
       [-0.76958637,  1.13909645, -1.42687381, -0.67324575, -1.16548715],
       [ 0.95139504,  0.03660653,  0.96255925,  1.01740693, -0.45432202],
       [ 1.3893695 , -0.29802241,  0.40177685, -0.26126767,  0.01459303],
       [ 0.83463712,  0.78538396,  0.54538353, -1.51484246,  1.1880103 ]])

In [28]:
# np.random.normal

In [29]:
np.random.randint(1,100)

14

In [30]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
runarr = np.random.randint(0,50,100)

In [35]:
runarr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5, 12, 29, 40, 49, 19, 47,  8,
       29, 34, 44,  8, 19, 10, 12, 31, 43, 23,  0, 41,  9, 47,  8, 36, 19,
       35, 28,  7, 10, 39, 38, 46,  9, 18,  7, 39, 15, 44,  0, 42, 12, 17,
       11, 15, 33, 29, 24, 36, 19, 35, 30, 10, 39, 20, 27,  8, 22, 26, 23,
       46, 47, 37, 22,  9, 45,  2, 18, 47, 28, 11, 10, 49, 30, 35, 28,  3,
       19, 20, 47, 14,  5,  5,  6, 24, 39, 37, 46,  7, 37,  4, 23])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
runarr.max()

49

In [38]:
runarr.min()

0

In [39]:
runarr.argmax()

13

In [40]:
runarr.argmin()

7

In [42]:
runarr.dtype

dtype('int32')

############################################################################################

# Class -3)  Numpy Index Selection

In [43]:
import numpy as np

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[8]

8

In [47]:
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [51]:
new_arr=arr/2

In [52]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
slice_of_arr = arr[0:6]

In [57]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
slice_of_arr[:]=99

In [59]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy = arr.copy()

In [68]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,35,40]])
arr_2d
                   

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [74]:
arr_2d.shape

(3, 3)

In [75]:
arr_2d[1]

array([20, 25, 30])

In [76]:
arr_2d[1,1]

25

In [77]:
arr_2d[1][1]

25

In [78]:
arr_2d[2,2]

40

In [79]:
arr_2d[2][2]

40

In [80]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [83]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [84]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
bool_arr=arr>4

In [89]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])

In [70]:
#########################################################################################################################

# 4) Class-4)  Numpy Operations

In [71]:
import numpy as np

In [92]:
arr= np.arange(0,111)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110])

In [93]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209, 210])

In [94]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 ])

In [95]:
arr ** 2

array([    0,     1,     4,     9,    16,    25,    36,    49,    64,
          81,   100,   121,   144,   169,   196,   225,   256,   289,
         324,   361,   400,   441,   484,   529,   576,   625,   676,
         729,   784,   841,   900,   961,  1024,  1089,  1156,  1225,
        1296,  1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,
        2025,  2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,
        2916,  3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,
        3969,  4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,
        5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,
        6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
        8100,  8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,
        9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449,
       11664, 11881, 12100], dtype=int32)

In [96]:
(arr+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11, 0.12,
       0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22, 0.23,
       0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33, 0.34,
       0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44, 0.45,
       0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56,
       0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67,
       0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78,
       0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89,
       0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ,
       1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 , 1.11,
       1.12])

In [97]:
arr + arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220])

In [98]:
1/arr

C:\Users\Kisalay\.conda\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276,
       0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
       0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
       0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816,
       0.02      , 0.01960784, 0.01923077, 0.01886792, 0.01851852,
       0.01818182, 0.01785714, 0.01754386, 0.01724138, 0.01694915,
       0.01666667, 0.01639344, 0.01612903, 0.01587302, 0.015625  ,
       0.01538462, 0.01515152, 0.01492537, 0.01470588, 0.01449275,
       0.01428571, 0.01408451, 0.01388889, 0.01369863, 0.01351

In [99]:
arr/arr

C:\Users\Kisalay\.conda\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481,
        5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189,
        5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ,
        6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958,
        6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ,
        7.07106781,  7.14142843,  7.21110255,  7.28010989,  7.34846923,
        7.41619849,  7.48331477,  7.54983444,  7.61577311,  7.68114575,
        7.74596669,  7.81024968,  7.87400787,  7.93725393,  8.        ,
        8.06225775,  8.1240384 ,  8.18535277,  8.24621125,  8.30

In [101]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265,
       -0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905,
       -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801,
       -0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,
        0.82682868, -0.02655115, -0.85551998, -0.89792768, -0.11

In [102]:
np.log(arr)

C:\Users\Kisalay\.conda\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ,
       3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
       4.24849524, 4.26267988, 4.27666612, 4.29045944, 4.30406

In [104]:
arr.sum()

6105

In [105]:
arr.max()

110

In [106]:
arr.min()

0

In [107]:
arr.mean()

55.0

In [108]:
arr_2dd=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [109]:
arr_2dd

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
arr_2dd.shape

(3, 4)

In [111]:
arr_2dd.sum()

78

In [112]:
arr_2dd.sum(axis=0)  #sum across row(sum of all the columns)

array([15, 18, 21, 24])

In [113]:
arr_2dd.sum(axis=1)  #sum across column(sum of all the rows)

array([10, 26, 42])

In [114]:
##########################################################################################################################

In [120]:
np.arange(36).reshape(6,6,1,1)

array([[[[ 0]],

        [[ 1]],

        [[ 2]],

        [[ 3]],

        [[ 4]],

        [[ 5]]],


       [[[ 6]],

        [[ 7]],

        [[ 8]],

        [[ 9]],

        [[10]],

        [[11]]],


       [[[12]],

        [[13]],

        [[14]],

        [[15]],

        [[16]],

        [[17]]],


       [[[18]],

        [[19]],

        [[20]],

        [[21]],

        [[22]],

        [[23]]],


       [[[24]],

        [[25]],

        [[26]],

        [[27]],

        [[28]],

        [[29]]],


       [[[30]],

        [[31]],

        [[32]],

        [[33]],

        [[34]],

        [[35]]]])