In [1]:
# Class 1)  Regarding the  tensor basics

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'1.1.0'

In [5]:
arr = np.array([1,2,3,4,5,6]) 

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr)

numpy.ndarray

In [9]:
# convert nd array  into  tensors

In [10]:
x= torch.from_numpy(arr)

In [11]:
x

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [12]:
type(x)

torch.Tensor

In [13]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [14]:
x

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [15]:
x.dtype

torch.int32

In [16]:
# Print the tensor object type
print(type(x))
print(x.type()) # this is more specific!

<class 'torch.Tensor'>
torch.IntTensor


In [17]:
arr2d = np.arange(0.0,18.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17.])

In [19]:
arr2d.reshape(6,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.]])

In [20]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17.])

In [21]:
x2 =  torch.from_numpy(arr2d)
x2

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17.], dtype=torch.float64)

In [22]:
arr[0]=99
arr

array([99,  2,  3,  4,  5,  6])

In [23]:
x

tensor([99,  2,  3,  4,  5,  6], dtype=torch.int32)

In [24]:
#########################################################

In [25]:
my_arr=np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_tensor=torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [28]:
my_other_tensor=torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [29]:
###### assigning new value to the index

In [30]:
my_arr[0]=99999999

In [31]:
my_arr

array([99999999,        1,        2,        3,        4,        5,
              6,        7,        8,        9])

In [32]:
my_other_tensor

tensor([99999999,        1,        2,        3,        4,        5,        6,
               7,        8,        9], dtype=torch.int32)

In [33]:
# it doesnt get affected
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [34]:
##########################################################

In [35]:
# # 1.4  Copying vs. sharing
# torch.from_numpy()
# torch.as_tensor()
# torch.tensor()

# There are a number of different functions available for creating tensors. When using torch.from_numpy() and torch.as_tensor(), the PyTorch tensor and the source NumPy array share the same memory. This means that changes to one affect the other. However, the torch.tensor() function always makes a copy.

In [38]:
import numpy as np
import torch
import pandas as pd

In [40]:
new_arr = np.array([1,2,3])
new_arr

array([1, 2, 3])

In [41]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [42]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [43]:
torch.FloatTensor(new_arr)

tensor([1., 2., 3.])

In [44]:
my_tensor_1=torch.tensor(new_arr)

In [45]:
my_tensor_1

tensor([1, 2, 3], dtype=torch.int32)

In [46]:
my_tensor_1.dtype

torch.int32

In [47]:
torch.empty(2,2)

tensor([[2.8362e+22, 4.7504e-43],
        [5.7397e-42, 0.0000e+00]])

In [48]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [49]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [50]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [56]:
torch.arange(0,10,2).reshape(5,1)

tensor([[0],
        [2],
        [4],
        [6],
        [8]])

In [57]:
torch.linspace(0,18,12).reshape(2,6)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909, 14.7273, 16.3636, 18.0000]])

In [58]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [59]:
my_tensor_2=torch.tensor([1,2,3])
my_tensor_2

tensor([1, 2, 3])

In [60]:
my_tensor_2.dtype

torch.int64

In [61]:
my_tensor_3= my_tensor_2.type(torch.int32)
my_tensor_3

tensor([1, 2, 3], dtype=torch.int32)

In [62]:
my_tensor_3.dtype

torch.int32

In [63]:
torch.rand(4,3)

tensor([[0.1644, 0.9250, 0.2398],
        [0.3107, 0.5958, 0.6147],
        [0.7612, 0.3182, 0.6559],
        [0.5858, 0.8457, 0.5280]])

In [64]:
torch.randn(4,3)

tensor([[ 0.6857, -1.0525,  0.4276],
        [-1.3029, -1.0422,  0.7831],
        [-1.1219, -1.5609, -0.3700],
        [-1.4079,  0.4160, -0.1620]])

In [65]:
torch.randint(low = 0,high=10,size=(5,5))

tensor([[6, 8, 5, 8, 6],
        [9, 4, 6, 4, 6],
        [4, 1, 4, 5, 8],
        [8, 5, 4, 8, 3],
        [3, 5, 8, 9, 0]])

In [67]:
x= torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [69]:
x.shape

torch.Size([2, 5])

In [70]:
###############################################################################

In [71]:
torch.rand_like(x)

tensor([[0.5388, 0.3062, 0.7367, 0.7334, 0.6981],
        [0.0913, 0.2194, 0.2301, 0.4712, 0.1882]])

In [72]:
torch.randn_like(x)

tensor([[-0.6184,  0.8787, -0.4481, -1.4903,  1.1735],
        [-0.9157,  0.9965, -0.8074, -0.4030, -0.2588]])

In [74]:
torch.randint_like(x,low=0,high=10)

tensor([[4., 6., 2., 8., 8.],
        [3., 2., 2., 4., 2.]])

In [75]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [77]:
data = np.array([1,2,3])
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3], dtype=torch.int32) torch.IntTensor


In [80]:
c=b.type(torch.long)

In [81]:
type(c)

torch.Tensor

In [82]:
c.dtype

torch.int64

In [83]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [84]:
type(x)

torch.Tensor

In [85]:
x.dtype

torch.int64

In [86]:
x.type()

'torch.LongTensor'

In [87]:
###########################################################################

In [88]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [90]:
x.shape

torch.Size([2, 3])

In [91]:
x.size()

torch.Size([2, 3])

In [92]:
x.device

device(type='cpu')

In [93]:
x.layout

torch.strided

In [94]:
##############################################################################################

# Class 3)  Tensor operations --- part 1)

In [95]:
import torch
import numpy as np

In [96]:
x= torch.arange(6).reshape(3,2)

In [97]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [98]:
type(x)

torch.Tensor

In [99]:
x[:,1]

tensor([1, 3, 5])

In [100]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [101]:
x= torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [103]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [105]:
########################################################

In [106]:
x= torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
z=x.view(2,5)

In [115]:
z

tensor([[234,   1,   2,  99,   4],
        [  5,   6,   7,   8,   9]])

In [116]:
x[0]=234
x

tensor([234,   1,   2,  99,   4,   5,   6,   7,   8,   9])

In [117]:
x.view(2,-1)

tensor([[234,   1,   2,  99,   4],
        [  5,   6,   7,   8,   9]])

In [118]:
x.view(-1,2)

tensor([[234,   1],
        [  2,  99],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [119]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,4.,6.])

In [120]:
a

tensor([1., 2., 3.])

In [121]:
b

tensor([4., 4., 6.])

In [122]:
a + b

tensor([5., 6., 9.])

In [123]:
torch.add(a,b)

tensor([5., 6., 9.])

In [124]:
a.mul(b)

tensor([ 4.,  8., 18.])

In [125]:
a.mul_(b)

tensor([ 4.,  8., 18.])

In [126]:
##############################################################################################

# Class 5)  Tensor Operations - Part 2)

In [127]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,4.,6.])

In [128]:
a * b # ELEMENT WISE operation

tensor([ 4.,  8., 18.])

In [129]:
a.mul(b)

tensor([ 4.,  8., 18.])

In [130]:
a.dot(b)

tensor(30.)

In [131]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

In [132]:
a.shape

torch.Size([2, 3])

In [133]:
b.shape

torch.Size([3, 2])

In [134]:
torch.mm(a,b)

tensor([[56., 62.],
        [80., 89.]])

In [135]:
a @ b

tensor([[56., 62.],
        [80., 89.]])

In [ ]:
###############################################

In [136]:
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


In [137]:
print(torch.mm(t1, t2).size())

RuntimeError: matrices expected, got 3D, 2D tensors at ..\aten\src\TH/generic/THTensorMath.cpp:956

In [138]:
####################################################

# L2 or Euclidian Norm

In [139]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)

# 2.2  Number of elements¶
See torch.numel()

Returns the number of elements in a tensor.

In [140]:
x = torch.ones(3,7)
x.numel()

21

In [3]:
import torch
import numpy as np
y = torch.tensor([[3.,4.,5.],[9.,4.,6.]])
y

tensor([[3., 4., 5.],
        [9., 4., 6.]])

In [10]:
z= torch.arange(2,9,dtype=torch.float32)
z

tensor([2., 3., 4., 5., 6., 7., 8.])

In [11]:
u = torch.norm(z)

In [12]:
u

tensor(14.2478)

In [ ]:
#####################################################################################################################3